feat: add github history update
CG-sc23/CG-sc23-Backend pull request #24
Opened 2023-11-03 14:44 UTC by white0825

사용자의 github 이력을 불러옵니다.

2023-11-03 14:52 UTC, K-osA requested changes

2023-11-03 14:52 UTC, K-osA commented on domo/domo_api/external_history/github.py
> +        user = User.objects.filter(id=user_id).get()
==
user = User.objects.get(id=user_id)

2023-11-03 14:52 UTC, K-osA commented on domo/domo_api/external_history/github.py
> +            return "No github url"
이렇게 문자열로 리턴하는거 만들어져있는 const.py에 상수로 정의해두고 갖다쓰면 좋을듯

2023-11-03 14:52 UTC, K-osA commented on domo/domo_api/external_history/github.py
> +            UserStack(user_id)
.?

2023-11-03 14:52 UTC, K-osA commented on domo/domo_api/external_history/github.py
> +            original_value = user_stack.get().code_amount
방금 알았는데 필터걸고 거기서 겟걸면 디비에 요청 두번한대 겟쓰는게 나을듯?

2023-11-06 03:31 UTC, white0825 commented on domo/domo_api/external_history/github.py
> +        user = User.objects.filter(id=user_id).get()
6b689e377fbbe242a5539d6a47cd6318010bda55

2023-11-06 03:32 UTC, white0825 commented on domo/domo_api/external_history/github.py
> +            return "No github url"
6b689e377fbbe242a5539d6a47cd6318010bda55

2023-11-06 03:32 UTC, white0825 commented on domo/domo_api/external_history/github.py
> +            UserStack(user_id)
6b689e377fbbe242a5539d6a47cd6318010bda55

2023-11-07 13:44 UTC, K-osA approved these changes

2023-11-07 13:46 UTC, merged